// Generated by ETERNAL_RESEARCH_CHILD/phase2_improvement_pipeline.ts
// Review before editing by hand.

export type ResearchImprovementKind = "HARVEY_LAB_GUARDRAIL" | "CITATION_ACCURACY" | "PRECEDENT_REVIEW" | "STANDARD_REVIEW" | "DRAFTING_SAFETY" | "DEMO_ENRICHMENT" | "ROADMAP";
export type ResearchImprovementPriority = "P0" | "P1" | "P2";
export type ResearchImprovementStatus = "READY_FOR_REVIEW" | "NEEDS_SOURCE_CHECK" | "BLOCKED_ACTIVE_MATTER";

export type ResearchImprovement = {
  id: string;
  title: string;
  kind: ResearchImprovementKind;
  priority: ResearchImprovementPriority;
  status: ResearchImprovementStatus;
  source: string;
  sourceType: "website" | "ebook" | "precedent" | "asset" | "log";
  targetArea: string;
  summary: string;
  reviewGate: string;
  labCriteria: string[];
};

export const RESEARCH_IMPROVEMENTS: ResearchImprovement[] = [
  {
    "id": "harvey-lab-client-matter-workspace",
    "title": "Harvey LAB guardrails for legal-agent work",
    "kind": "HARVEY_LAB_GUARDRAIL",
    "priority": "P0",
    "status": "READY_FOR_REVIEW",
    "source": "https://www.harvey.ai/blog/introducing-harveys-legal-agent-benchmark",
    "sourceType": "website",
    "targetArea": "improvement lab, review queue, and safe drafting",
    "summary": "Use LAB concepts as a product rubric: closed matter workspace, reviewable work product, expert binary criteria, and all-pass grading.",
    "reviewGate": "Generated work must remain a review artifact for counsel, not case-specific legal advice.",
    "labCriteria": [
      "Matter materials are grouped before drafting.",
      "Output is reviewable work product.",
      "Every criterion is pass/fail.",
      "Task is complete only when all required criteria pass."
    ]
  },
  {
    "id": "demo-enrichment-attached-assets-15-week-action-plan-omni-modal-m",
    "source": "Attached_Assets/15_WEEK_ACTION_PLAN_OMNI_MODAL.md",
    "title": "Demo case enrichment",
    "kind": "DEMO_ENRICHMENT",
    "priority": "P1",
    "status": "READY_FOR_REVIEW",
    "sourceType": "asset",
    "targetArea": "demo cases and infra arbitration browser",
    "summary": "Candidate source for richer timelines, claim matrices, contradiction lists, and counsel-review issue outlines.",
    "reviewGate": "Keep facts tied to source files and label synthetic/demo material clearly.",
    "labCriteria": [
      "Chronology has dated source anchors.",
      "Internal inconsistencies are listed separately.",
      "Review output is framed as an issue outline, not legal advice."
    ]
  },
  {
    "id": "standard-review-attached-assets-antigravity-logbook-md",
    "source": "Attached_Assets/Antigravity Logbook.md",
    "title": "Standards and clause review",
    "kind": "STANDARD_REVIEW",
    "priority": "P1",
    "status": "NEEDS_SOURCE_CHECK",
    "sourceType": "asset",
    "targetArea": "standards index and verification engine",
    "summary": "Candidate source for standards coverage, clause mapping, and source-backed forensic or infrastructure checks.",
    "reviewGate": "Clause language must be verified against the governing standard before being used as a filing claim.",
    "labCriteria": [
      "Standard code, year, title, and clause are recorded.",
      "Scope matches the tested material or contract issue.",
      "Superseded standards are labeled before use."
    ]
  },
  {
    "id": "standard-review-attached-assets-antigravitylogbook-md",
    "source": "Attached_Assets/AntigravityLogbook.md",
    "title": "Standards and clause review",
    "kind": "STANDARD_REVIEW",
    "priority": "P1",
    "status": "NEEDS_SOURCE_CHECK",
    "sourceType": "asset",
    "targetArea": "standards index and verification engine",
    "summary": "Candidate source for standards coverage, clause mapping, and source-backed forensic or infrastructure checks.",
    "reviewGate": "Clause language must be verified against the governing standard before being used as a filing claim.",
    "labCriteria": [
      "Standard code, year, title, and clause are recorded.",
      "Scope matches the tested material or contract issue.",
      "Superseded standards are labeled before use."
    ]
  },
  {
    "id": "demo-enrichment-attached-assets-arbitrate-md",
    "source": "Attached_Assets/ARBITRATE.MD",
    "title": "Demo case enrichment",
    "kind": "DEMO_ENRICHMENT",
    "priority": "P1",
    "status": "READY_FOR_REVIEW",
    "sourceType": "asset",
    "targetArea": "demo cases and infra arbitration browser",
    "summary": "Candidate source for richer timelines, claim matrices, contradiction lists, and counsel-review issue outlines.",
    "reviewGate": "Keep facts tied to source files and label synthetic/demo material clearly.",
    "labCriteria": [
      "Chronology has dated source anchors.",
      "Internal inconsistencies are listed separately.",
      "Review output is framed as an issue outline, not legal advice."
    ]
  },
  {
    "id": "citation-accuracy-attached-assets-citation-accuracy-and-6month-roa",
    "source": "Attached_Assets/CITATION_ACCURACY_AND_6MONTH_ROADMAP.md",
    "title": "Citation and precedent accuracy upgrade",
    "kind": "CITATION_ACCURACY",
    "priority": "P0",
    "status": "NEEDS_SOURCE_CHECK",
    "sourceType": "asset",
    "targetArea": "citation gate and precedent registry",
    "summary": "Candidate source for improving citation allowlists, status tiers, source URLs, and blocked-from-draft handling.",
    "reviewGate": "Do not mark VERIFIED until the citation is checked against an authoritative source.",
    "labCriteria": [
      "Each citation has status, source URL, and status note.",
      "Unknown citations remain blocked from draft output.",
      "Paragraph-specific claims are blocked unless paragraph text is verified."
    ]
  },
  {
    "id": "citation-accuracy-attached-assets-citation-risk-reduction-plan-v1-",
    "source": "Attached_Assets/CITATION_RISK_REDUCTION_PLAN_v1.md",
    "title": "Citation and precedent accuracy upgrade",
    "kind": "CITATION_ACCURACY",
    "priority": "P0",
    "status": "NEEDS_SOURCE_CHECK",
    "sourceType": "asset",
    "targetArea": "citation gate and precedent registry",
    "summary": "Candidate source for improving citation allowlists, status tiers, source URLs, and blocked-from-draft handling.",
    "reviewGate": "Do not mark VERIFIED until the citation is checked against an authoritative source.",
    "labCriteria": [
      "Each citation has status, source URL, and status note.",
      "Unknown citations remain blocked from draft output.",
      "Paragraph-specific claims are blocked unless paragraph text is verified."
    ]
  },
  {
    "id": "citation-accuracy-attached-assets-genspark-md",
    "source": "Attached_Assets/genspark.md",
    "title": "Citation and precedent accuracy upgrade",
    "kind": "CITATION_ACCURACY",
    "priority": "P0",
    "status": "NEEDS_SOURCE_CHECK",
    "sourceType": "asset",
    "targetArea": "citation gate and precedent registry",
    "summary": "Candidate source for improving citation allowlists, status tiers, source URLs, and blocked-from-draft handling.",
    "reviewGate": "Do not mark VERIFIED until the citation is checked against an authoritative source.",
    "labCriteria": [
      "Each citation has status, source URL, and status note.",
      "Unknown citations remain blocked from draft output.",
      "Paragraph-specific claims are blocked unless paragraph text is verified."
    ]
  },
  {
    "id": "demo-enrichment-attached-assets-grok-md",
    "source": "Attached_Assets/grok.md",
    "title": "Demo case enrichment",
    "kind": "DEMO_ENRICHMENT",
    "priority": "P1",
    "status": "READY_FOR_REVIEW",
    "sourceType": "asset",
    "targetArea": "demo cases and infra arbitration browser",
    "summary": "Candidate source for richer timelines, claim matrices, contradiction lists, and counsel-review issue outlines.",
    "reviewGate": "Keep facts tied to source files and label synthetic/demo material clearly.",
    "labCriteria": [
      "Chronology has dated source anchors.",
      "Internal inconsistencies are listed separately.",
      "Review output is framed as an issue outline, not legal advice."
    ]
  },
  {
    "id": "citation-accuracy-attached-assets-land-aq-dig-deeper-thrice-and-ge",
    "source": "Attached_Assets/land aq dig deeper thrice and get more bett.txt",
    "title": "Citation and precedent accuracy upgrade",
    "kind": "CITATION_ACCURACY",
    "priority": "P0",
    "status": "NEEDS_SOURCE_CHECK",
    "sourceType": "asset",
    "targetArea": "citation gate and precedent registry",
    "summary": "Candidate source for improving citation allowlists, status tiers, source URLs, and blocked-from-draft handling.",
    "reviewGate": "Do not mark VERIFIED until the citation is checked against an authoritative source.",
    "labCriteria": [
      "Each citation has status, source URL, and status note.",
      "Unknown citations remain blocked from draft output.",
      "Paragraph-specific claims are blocked unless paragraph text is verified."
    ]
  },
  {
    "id": "citation-accuracy-attached-assets-master-combined-prompt-md",
    "source": "Attached_Assets/MASTER COMBINED PROMPT.md",
    "title": "Citation and precedent accuracy upgrade",
    "kind": "CITATION_ACCURACY",
    "priority": "P0",
    "status": "NEEDS_SOURCE_CHECK",
    "sourceType": "asset",
    "targetArea": "citation gate and precedent registry",
    "summary": "Candidate source for improving citation allowlists, status tiers, source URLs, and blocked-from-draft handling.",
    "reviewGate": "Do not mark VERIFIED until the citation is checked against an authoritative source.",
    "labCriteria": [
      "Each citation has status, source URL, and status note.",
      "Unknown citations remain blocked from draft output.",
      "Paragraph-specific claims are blocked unless paragraph text is verified."
    ]
  },
  {
    "id": "citation-accuracy-attached-assets-pasted-prompt-for-software-engin",
    "source": "Attached_Assets/Pasted-PROMPT-FOR-SOFTWARE-ENGINEER-AI-AGENT-You-are-India-s-f_1775049215254.txt",
    "title": "Citation and precedent accuracy upgrade",
    "kind": "CITATION_ACCURACY",
    "priority": "P0",
    "status": "NEEDS_SOURCE_CHECK",
    "sourceType": "asset",
    "targetArea": "citation gate and precedent registry",
    "summary": "Candidate source for improving citation allowlists, status tiers, source URLs, and blocked-from-draft handling.",
    "reviewGate": "Do not mark VERIFIED until the citation is checked against an authoritative source.",
    "labCriteria": [
      "Each citation has status, source URL, and status note.",
      "Unknown citations remain blocked from draft output.",
      "Paragraph-specific claims are blocked unless paragraph text is verified."
    ]
  },
  {
    "id": "citation-accuracy-attached-assets-prompt-for-your-senior-software-",
    "source": "Attached_Assets/PROMPT FOR YOUR SENIOR SOFTWARE ENGINEER.md",
    "title": "Citation and precedent accuracy upgrade",
    "kind": "CITATION_ACCURACY",
    "priority": "P0",
    "status": "NEEDS_SOURCE_CHECK",
    "sourceType": "asset",
    "targetArea": "citation gate and precedent registry",
    "summary": "Candidate source for improving citation allowlists, status tiers, source URLs, and blocked-from-draft handling.",
    "reviewGate": "Do not mark VERIFIED until the citation is checked against an authoritative source.",
    "labCriteria": [
      "Each citation has status, source URL, and status note.",
      "Unknown citations remain blocked from draft output.",
      "Paragraph-specific claims are blocked unless paragraph text is verified."
    ]
  },
  {
    "id": "demo-enrichment-real-cases-infra-arb-05-landscape-township-2026-",
    "source": "real_cases/INFRA_ARB_05_LANDSCAPE_TOWNSHIP_2026/ARB_APPOINTMENT_APPLICATION_SEC11.lex",
    "title": "Demo case enrichment",
    "kind": "DEMO_ENRICHMENT",
    "priority": "P1",
    "status": "READY_FOR_REVIEW",
    "sourceType": "precedent",
    "targetArea": "demo cases and infra arbitration browser",
    "summary": "Candidate source for richer timelines, claim matrices, contradiction lists, and counsel-review issue outlines.",
    "reviewGate": "Keep facts tied to source files and label synthetic/demo material clearly.",
    "labCriteria": [
      "Chronology has dated source anchors.",
      "Internal inconsistencies are listed separately.",
      "Review output is framed as an issue outline, not legal advice."
    ]
  },
  {
    "id": "demo-enrichment-real-cases-infra-arb-05-landscape-township-2026-",
    "source": "real_cases/INFRA_ARB_05_LANDSCAPE_TOWNSHIP_2026/Case_Facts_Timeline.md",
    "title": "Demo case enrichment",
    "kind": "DEMO_ENRICHMENT",
    "priority": "P1",
    "status": "READY_FOR_REVIEW",
    "sourceType": "precedent",
    "targetArea": "demo cases and infra arbitration browser",
    "summary": "Candidate source for richer timelines, claim matrices, contradiction lists, and counsel-review issue outlines.",
    "reviewGate": "Keep facts tied to source files and label synthetic/demo material clearly.",
    "labCriteria": [
      "Chronology has dated source anchors.",
      "Internal inconsistencies are listed separately.",
      "Review output is framed as an issue outline, not legal advice."
    ]
  },
  {
    "id": "standard-review-real-cases-infra-arb-05-landscape-township-2026-",
    "source": "real_cases/INFRA_ARB_05_LANDSCAPE_TOWNSHIP_2026/Claim_Matrix_Verified_Pending.md",
    "title": "Standards and clause review",
    "kind": "STANDARD_REVIEW",
    "priority": "P1",
    "status": "NEEDS_SOURCE_CHECK",
    "sourceType": "precedent",
    "targetArea": "standards index and verification engine",
    "summary": "Candidate source for standards coverage, clause mapping, and source-backed forensic or infrastructure checks.",
    "reviewGate": "Clause language must be verified against the governing standard before being used as a filing claim.",
    "labCriteria": [
      "Standard code, year, title, and clause are recorded.",
      "Scope matches the tested material or contract issue.",
      "Superseded standards are labeled before use."
    ]
  }
];
